---
# tasks file for nutanix_role_prism_proxy
  - name: Check prism_proxy_name is provided
    fail:
      msg: var prism_proxy_name is required
    when:
      - prism_proxy_name is not defined

  - name: Check prism_proxy_address is provided
    fail:
      msg: var prism_proxy_address is required
    when:
      - prism_proxy_address is not defined

  - name: Check prism_proxy_port is provided
    fail:
      msg: var prism_proxy_port is required
    when:
      - prism_proxy_port is not defined

  - name: Check prism_proxy_types is provided
    fail:
      msg: var prism_proxy_types is required
    when:
      - prism_proxy_types is not defined

  - name: Gather proxy configuration from cluster
    uri:
      url: "{{ prism_api_v2 }}/http_proxies"
      method: GET
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
    register: prism_configured_proxies

  # - debug:
  #     var: prism_configured_proxies
  #
  - name: compare current proxy name to new proxy name
    set_fact:
      prism_proxy_name_mismatch: True
    when:
    - prism_configured_proxies.json.metadata.count == 1
    - prism_configured_proxies.json.entities[0].name != prism_proxy_name

  # - debug:
  #     var: prism_proxy_name_mismatch
  #
  - name: compare current proxy config to new proxy config
    set_fact:
      prism_proxy_config_mismatch: True
    when:
    - prism_configured_proxies.json.metadata.count == 1
    - ( prism_configured_proxies.json.entities[0].address != prism_proxy_address or
        prism_configured_proxies.json.entities[0].port != prism_proxy_port or
        prism_configured_proxies.json.entities[0].username != prism_proxy_username | default(None) )

  # - debug:
  #     var: prism_proxy_config_mismatch
  #
  - name: compare configured proxy types to defined proxy types
    set_fact:
      prism_proxy_extra_type: True
    when:
    - prism_configured_proxies.json.metadata.count == 1
    - item not in prism_proxy_types
    with_items: "{{ prism_configured_proxies.json.entities[0].proxy_types }}"

  # - debug:
  #     var: prism_proxy_extra_type
  #
  - name: compare defined proxy types to configured proxy types
    set_fact:
      prism_proxy_missing_type: True
    when:
    - prism_configured_proxies.json.metadata.count == 1
    - item not in prism_configured_proxies.json.entities[0].proxy_types
    with_items: "{{ prism_proxy_types }}"

  # - debug:
  #     var: prism_proxy_missing_type
  #
  - name: delete prism proxy configuration to fix name mismatch
    uri:
      url: "{{ prism_api_v2 }}/http_proxies/{{ prism_configured_proxies.json.entities[0].name }}"
      method: DELETE
      validate_certs: "{{ validate_certs }}"
      body_format: json
      headers:
        Authorization: "{{ prism_api_auth }}"
      status_code: 204
      return_content: yes
    changed_when: true
    register: proxy_deleted
    when:
      - prism_configured_proxies.json.metadata.count == 1
      - prism_proxy_name_mismatch is defined

  - name: create proxy configuration
    uri:
      url: "{{ prism_api_v2 }}/http_proxies"
      method: POST
      validate_certs: "{{ validate_certs }}"
      body: "{{ lookup('template', 'proxy.j2') | from_yaml | to_json }}"
      body_format: json
      status_code: 201
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
    register: prism_create_proxy
    when:
      - prism_configured_proxies.json.metadata.count == 0 or prism_proxy_name_mismatch is defined

  - name: update proxy configuration
    uri:
      url: "{{ prism_api_v2 }}/http_proxies"
      method: PUT
      validate_certs: "{{ validate_certs }}"
      body: "{{ lookup('template', 'proxy.j2') | from_yaml | to_json }}"
      body_format: json
      status_code: 200
      headers:
        Authorization: "{{ prism_api_auth }}"
      return_content: yes
    register: prism_update_proxy
    changed_when: prism_update_proxy.json.value == true
    when:
      - prism_configured_proxies.json.metadata.count == 1
      - prism_proxy_name_mismatch is not defined
      - prism_proxy_config_mismatch is defined

  - name: Wait HTTP proxy update to be completed
    block:
      - name: Checking HTTP proxy configuration
        uri:
          url: "{{ prism_api_v2 }}/http_proxies"
          method: GET
          validate_certs: "{{ validate_certs }}"
          status_code: 200
          headers:
            Authorization: "{{ prism_api_auth }}"
        register: prism_proxy_status
        until:
          - prism_proxy_status.json.entities[0].name == prism_proxy_name
          - prism_proxy_status.json.entities[0].address == prism_proxy_address
          - prism_proxy_status.json.entities[0].port == prism_proxy_port
          - prism_proxy_status.json.entities[0].username == prism_proxy_username | default(None)
        retries: 60
        delay: 10
        when: prism_create_proxy is defined or prism_update_proxy is defined
